version: "3"
services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3308:3306
    restart: always
    volumes:
      - ./data:/var/lib/mysql

    networks:
      - test

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
  node_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env

    volumes:
      - ./:/app

    networks:
      - test
    depends_on:
      database:
        condition: service_healthy

networks:
  test:
    driver: bridge
