version: "3"
services:
  node_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080   

    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env
    restart: always
    depends_on:
      - database
  database:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3307:3306
volumes:
  db_data: